services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret123
      - MYSQL_DATABASE=minitwitter
      - MYSQL_USER=minitwitter
      - MYSQL_PASSWORD=supersecret123
    ports:
      - 3306:3306
    volumes:
      - m223_project_mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 12

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=supersecret123
    ports:
      - 9200:80
    depends_on:
      mariadb:
        condition: service_healthy

  application:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=mariadb
      - DB_USER=minitwitter
      - DB_PASSWORD=supersecret123
      - DB_NAME=minitwitter
    ports:
      - 4200:4200
    volumes:
      - node_modules:/app/node_modules
    depends_on:
      mariadb:
        condition: service_healthy


volumes:
  m223_project_mariadb:
  node_modules:
